# Generated by Django 5.1.7 on 2025-03-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_expensecategory_rename_habitboarduser_boarduser_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boarduser",
            old_name="habit_board",
            new_name="board",
        ),
    ]
