# Generated by Django 5.1.7 on 2025-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_expensecategory_board_expensecategory_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensesplit",
            name="split_type",
        ),
        migrations.AddField(
            model_name="expense",
            name="split_type",
            field=models.CharField(
                choices=[
                    ("equally", "Equally"),
                    ("percentage", "Percentage"),
                    ("amount", "Amount"),
                ],
                default="equally",
                max_length=10,
            ),
        ),
    ]
