# Generated by Django 5.1.7 on 2025-03-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_remove_expensesplit_split_type_expense_split_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="split_type",
            field=models.CharField(
                choices=[("equally", "Equally"), ("amount", "Amount")],
                default="equally",
                max_length=10,
            ),
        ),
    ]
