# Generated by Django 4.2.23 on 2025-09-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_expense_split_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='created_by',
        ),
    ]
