# Generated by Django 4.2.23 on 2026-01-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_expensecategory_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='paid_by',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='expensesplit',
            old_name='amount',
            new_name='share_amount',
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('amount', 'Amount'), ('percentage', 'Percentage')], default='equal', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='expensesplit',
            unique_together={('expense', 'user')},
        ),
    ]
