# Generated by Django 4.2.23 on 2026-01-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_rename_paid_by_expense_payer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='id',
        ),
    ]
