# Generated by Django 4.2.23 on 2026-01-15 17:51

from django.db import migrations, models
import habits.models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=habits.models.get_today),
        ),
    ]
