# Generated by Django 4.2.23 on 2026-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0014_alter_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='description',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='emoji',
            field=models.CharField(default='💰', max_length=10),
        ),
    ]
