# Generated by Django 5.1.7 on 2026-03-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0016_add_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habits.board'),
        ),
    ]
