# Generated by Django 5.1.7 on 2026-07-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0019_alter_board_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
    ]
