# Generated by Django 5.1.7 on 2026-08-03 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_created_by(apps, schema_editor):
    Expense = apps.get_model('habits', 'Expense')
    Expense.objects.filter(created_by__isnull=True).update(created_by=models.F('payer'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0022_boarduser_notify_on_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_created_by, noop),
    ]
